"""add_token_usage_history_table

Revision ID: 423844e2e2b8
Revises: 86fd0f958e62
Create Date: 2025-08-21 11:24:11.805537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '423844e2e2b8'
down_revision: Union[str, None] = '86fd0f958e62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_usage_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.String(length=100), nullable=False),
    sa.Column('used_tokens', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('used_tokens >= 0', name='check_used_tokens_positive_history'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_token_usage_created_at', 'token_usage_history', ['created_at'], unique=False)
    op.create_index('idx_token_usage_request_id', 'token_usage_history', ['request_id'], unique=False)
    op.create_index('idx_token_usage_token_id', 'token_usage_history', ['token_id'], unique=False)
    op.create_index(op.f('ix_token_usage_history_id'), 'token_usage_history', ['id'], unique=False)
    op.create_index(op.f('ix_token_usage_history_request_id'), 'token_usage_history', ['request_id'], unique=True)
    op.create_index(op.f('ix_token_usage_history_token_id'), 'token_usage_history', ['token_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_usage_history_token_id'), table_name='token_usage_history')
    op.drop_index(op.f('ix_token_usage_history_request_id'), table_name='token_usage_history')
    op.drop_index(op.f('ix_token_usage_history_id'), table_name='token_usage_history')
    op.drop_index('idx_token_usage_token_id', table_name='token_usage_history')
    op.drop_index('idx_token_usage_request_id', table_name='token_usage_history')
    op.drop_index('idx_token_usage_created_at', table_name='token_usage_history')
    op.drop_table('token_usage_history')
    # ### end Alembic commands ###
