
"""Remove unique constraint from payments.plan_code

Revision ID: 4378b797e0a0
Revises: cc5a0acd712c
Create Date: 2025-08-22 16:44:32.750312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4378b797e0a0'
down_revision: Union[str, None] = 'cc5a0acd712c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove unique constraint from payments.plan_code
    op.drop_index('ix_payments_plan_code', table_name='payments')
    op.create_index(op.f('ix_payments_plan_code'), 'payments', ['plan_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Restore unique constraint to payments.plan_code
    op.drop_index(op.f('ix_payments_plan_code'), table_name='payments')
    op.create_index('ix_payments_plan_code', 'payments', ['plan_code'], unique=True)
    # ### end Alembic commands ###