"""Add overage_payments table for service overage billing

Revision ID: b85d427bc185
Revises: 71d6a6fb97bd
Create Date: 2025-08-20 16:03:42.214294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b85d427bc185'
down_revision: Union[str, None] = '71d6a6fb97bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('overage_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.String(length=50), nullable=False),
    sa.Column('plan_code', sa.String(length=50), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('overage_unit_price', sa.Integer(), nullable=False),
    sa.Column('overage_tokens', sa.Float(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.payment_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_overage_payment_id', 'overage_payments', ['payment_id'], unique=False)
    op.create_index('idx_overage_plan_code', 'overage_payments', ['plan_code'], unique=False)
    op.create_index(op.f('ix_overage_payments_id'), 'overage_payments', ['id'], unique=False)
    op.create_index(op.f('ix_overage_payments_payment_id'), 'overage_payments', ['payment_id'], unique=False)
    op.create_index(op.f('ix_overage_payments_plan_code'), 'overage_payments', ['plan_code'], unique=False)
    op.drop_table('transcription_requests_20250820_001')
    op.drop_table('transcription_responses_20250820_001')
    op.alter_column('api_tokens', 'token_key',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('api_tokens', 'api_key',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_tokens', 'api_key',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('api_tokens', 'token_key',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_table('transcription_responses_20250820_001',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('transcribed_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('summary_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('language_detected', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('duration', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('word_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('service_provider', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('audio_duration_minutes', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('tokens_used', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('response_data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('request_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True)
    )
    op.create_table('transcription_requests_20250820_001',
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('file_extension', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('processing_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('request_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('duration', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('service_provider', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('client_ip', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('response_rid', sa.VARCHAR(length=100), autoincrement=False, nullable=True)
    )
    op.drop_index(op.f('ix_overage_payments_plan_code'), table_name='overage_payments')
    op.drop_index(op.f('ix_overage_payments_payment_id'), table_name='overage_payments')
    op.drop_index(op.f('ix_overage_payments_id'), table_name='overage_payments')
    op.drop_index('idx_overage_plan_code', table_name='overage_payments')
    op.drop_index('idx_overage_payment_id', table_name='overage_payments')
    op.drop_table('overage_payments')
    # ### end Alembic commands ###
