"""Rename daglo_response_data to response_data

Revision ID: 47b45ba7eb91
Revises: ccf84eae0ab4
Create Date: 2025-08-13 13:47:21.346634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47b45ba7eb91'
down_revision: Union[str, None] = 'ccf84eae0ab4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcription_responses', sa.Column('response_data', sa.Text(), nullable=True))
    op.drop_column('transcription_responses', 'daglo_response_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcription_responses', sa.Column('daglo_response_data', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('transcription_responses', 'response_data')
    # ### end Alembic commands ###
