"""Add missing columns to transcription_requests

Revision ID: 71d6a6fb97bd
Revises: ec81596dd3fb
Create Date: 2025-08-20 13:49:05.643139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71d6a6fb97bd'
down_revision: Union[str, None] = 'ec81596dd3fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_tokens', sa.Column('api_key', sa.String(length=255), nullable=True))
    op.alter_column('api_tokens', 'token_key',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('api_tokens', 'token_hash_key')
    op.add_column('transcription_requests', sa.Column('service_provider', sa.String(length=50), nullable=True))
    op.add_column('transcription_requests', sa.Column('client_ip', sa.String(length=50), nullable=True))
    op.add_column('transcription_requests', sa.Column('response_rid', sa.String(length=100), nullable=True))
    op.drop_column('transcription_requests', 'daglo_rid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcription_requests', sa.Column('daglo_rid', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('transcription_requests', 'response_rid')
    op.drop_column('transcription_requests', 'client_ip')
    op.drop_column('transcription_requests', 'service_provider')
    op.add_column('api_tokens', sa.Column('token_hash_key', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.alter_column('api_tokens', 'token_key',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('api_tokens', 'api_key')
    # ### end Alembic commands ###
