"""add_service_tokens_table

Revision ID: 76167c484377
Revises: b85d427bc185
Create Date: 2025-08-21 11:10:14.046806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76167c484377'
down_revision: Union[str, None] = 'b85d427bc185'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_uuid', sa.String(length=36), nullable=False),
    sa.Column('token_id', sa.String(length=100), nullable=False),
    sa.Column('quota_tokens', sa.Float(), nullable=False),
    sa.Column('used_tokens', sa.Float(), nullable=False),
    sa.Column('token_expiry_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("status IN ('정상', '만료', '일시중지')", name='check_status_valid'),
    sa.CheckConstraint('quota_tokens >= 0', name='check_quota_tokens_positive'),
    sa.CheckConstraint('used_tokens >= 0', name='check_used_tokens_positive'),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.user_uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_uuid', 'token_id', name='uq_user_token')
    )
    op.create_index('idx_service_token_expiry', 'service_tokens', ['token_expiry_date'], unique=False)
    op.create_index('idx_service_token_status', 'service_tokens', ['status'], unique=False)
    op.create_index('idx_service_token_user_uuid', 'service_tokens', ['user_uuid'], unique=False)
    op.create_index(op.f('ix_service_tokens_id'), 'service_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_service_tokens_token_id'), 'service_tokens', ['token_id'], unique=False)
    op.create_index(op.f('ix_service_tokens_user_uuid'), 'service_tokens', ['user_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_tokens_user_uuid'), table_name='service_tokens')
    op.drop_index(op.f('ix_service_tokens_token_id'), table_name='service_tokens')
    op.drop_index(op.f('ix_service_tokens_id'), table_name='service_tokens')
    op.drop_index('idx_service_token_user_uuid', table_name='service_tokens')
    op.drop_index('idx_service_token_status', table_name='service_tokens')
    op.drop_index('idx_service_token_expiry', table_name='service_tokens')
    op.drop_table('service_tokens')
    # ### end Alembic commands ###
