"""add_table_comments_korean

Revision ID: 78f7cdf2dfc7
Revises: ec8cc4ae1507
Create Date: 2025-08-21 15:02:19.404663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78f7cdf2dfc7'
down_revision: Union[str, None] = 'ec8cc4ae1507'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'api_tokens',
        '사용자별 API 인증 토큰을 관리하는 테이블',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'api_usage_logs',
        'API 호출 이력과 사용량을 추적하는 테이블',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'login_logs',
        '사용자 로그인 이력을 추적하는 테이블',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'monthly_billings',
        '사용자별 월별 사용량과 요금을 관리하는 테이블',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'overage_payments',
        '서비스 초과 사용량에 대한 결재 상세 정보를 저장하는 테이블',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'payments',
        '사용자 결재 정보를 관리하는 테이블',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'service_tokens',
        '사용자별 토큰 할당 및 사용량을 관리하는 테이블',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'subscription_payments',
        '구독 요금제 결재 상세 정보를 저장하는 테이블',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'subscription_plans',
        '서비스 구독 요금제 정보를 관리하는 테이블',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'token_payments',
        '토큰 구매 결재 상세 정보를 저장하는 테이블',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'token_usage_history',
        '토큰 사용 이력을 추적하는 테이블',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'transcription_requests',
        '음성 파일의 텍스트 변환 요청 정보를 저장하는 테이블',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'transcription_responses',
        '음성 파일의 텍스트 변환 결과를 저장하는 테이블',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'users',
        '사용자 정보를 관리하는 테이블',
        existing_comment=None,
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        'users',
        existing_comment='사용자 정보를 관리하는 테이블',
        schema=None
    )
    op.drop_table_comment(
        'transcription_responses',
        existing_comment='음성 파일의 텍스트 변환 결과를 저장하는 테이블',
        schema=None
    )
    op.drop_table_comment(
        'transcription_requests',
        existing_comment='음성 파일의 텍스트 변환 요청 정보를 저장하는 테이블',
        schema=None
    )
    op.drop_table_comment(
        'token_usage_history',
        existing_comment='토큰 사용 이력을 추적하는 테이블',
        schema=None
    )
    op.drop_table_comment(
        'token_payments',
        existing_comment='토큰 구매 결재 상세 정보를 저장하는 테이블',
        schema=None
    )
    op.drop_table_comment(
        'subscription_plans',
        existing_comment='서비스 구독 요금제 정보를 관리하는 테이블',
        schema=None
    )
    op.drop_table_comment(
        'subscription_payments',
        existing_comment='구독 요금제 결재 상세 정보를 저장하는 테이블',
        schema=None
    )
    op.drop_table_comment(
        'service_tokens',
        existing_comment='사용자별 토큰 할당 및 사용량을 관리하는 테이블',
        schema=None
    )
    op.drop_table_comment(
        'payments',
        existing_comment='사용자 결재 정보를 관리하는 테이블',
        schema=None
    )
    op.drop_table_comment(
        'overage_payments',
        existing_comment='서비스 초과 사용량에 대한 결재 상세 정보를 저장하는 테이블',
        schema=None
    )
    op.drop_table_comment(
        'monthly_billings',
        existing_comment='사용자별 월별 사용량과 요금을 관리하는 테이블',
        schema=None
    )
    op.drop_table_comment(
        'login_logs',
        existing_comment='사용자 로그인 이력을 추적하는 테이블',
        schema=None
    )
    op.drop_table_comment(
        'api_usage_logs',
        existing_comment='API 호출 이력과 사용량을 추적하는 테이블',
        schema=None
    )
    op.drop_table_comment(
        'api_tokens',
        existing_comment='사용자별 API 인증 토큰을 관리하는 테이블',
        schema=None
    )
    # ### end Alembic commands ###
