"""change_service_tokens_to_numeric_precision

Revision ID: 86fd0f958e62
Revises: 76167c484377
Create Date: 2025-08-21 11:15:32.116400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86fd0f958e62'
down_revision: Union[str, None] = '76167c484377'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('service_tokens', 'quota_tokens',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('service_tokens', 'used_tokens',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('service_tokens', 'used_tokens',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('service_tokens', 'quota_tokens',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    # ### end Alembic commands ###
