"""add service provider, audio duration minutes, and tokens used columns

Revision ID: ccf84eae0ab4
Revises: 7cf574be5041
Create Date: 2025-08-12 14:51:47.790233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccf84eae0ab4'
down_revision: Union[str, None] = '7cf574be5041'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcription_responses', sa.Column('service_provider', sa.String(length=50), nullable=True))
    op.add_column('transcription_responses', sa.Column('audio_duration_minutes', sa.Float(), nullable=True))
    op.add_column('transcription_responses', sa.Column('tokens_used', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcription_responses', 'tokens_used')
    op.drop_column('transcription_responses', 'audio_duration_minutes')
    op.drop_column('transcription_responses', 'service_provider')
    # ### end Alembic commands ###
