"""reorder_transcription_response_columns

Revision ID: dd014ace9a00
Revises: 47b45ba7eb91
Create Date: 2025-08-14 09:01:50.295180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd014ace9a00'
down_revision: Union[str, None] = '47b45ba7eb91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
