"""Add duration column to transcription_requests

Revision ID: ec81596dd3fb
Revises: db3cb9363c0b
Create Date: 2025-08-15 11:39:47.523923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec81596dd3fb'
down_revision: Union[str, None] = 'db3cb9363c0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcription_requests', sa.Column('duration', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcription_requests', 'duration')
    # ### end Alembic commands ###
