"""add_korean_logical_names_to_all_tables_and_columns

Revision ID: ec8cc4ae1507
Revises: 423844e2e2b8
Create Date: 2025-08-21 13:17:33.251103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec8cc4ae1507'
down_revision: Union[str, None] = '423844e2e2b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_tokens', 'id',
               existing_type=sa.INTEGER(),
               comment='API토큰일련번호',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('api_tokens', 'user_uuid',
               existing_type=sa.VARCHAR(length=36),
               comment='사용자고유식별자',
               existing_nullable=False)
    op.alter_column('api_tokens', 'token_id',
               existing_type=sa.VARCHAR(length=100),
               comment='토큰식별자',
               existing_nullable=False)
    op.alter_column('api_tokens', 'token_name',
               existing_type=sa.VARCHAR(length=100),
               comment='토큰명',
               existing_nullable=True)
    op.alter_column('api_tokens', 'token_key',
               existing_type=sa.VARCHAR(length=255),
               comment='토큰키해시값',
               existing_nullable=False)
    op.alter_column('api_tokens', 'api_key',
               existing_type=sa.VARCHAR(length=255),
               comment='API키',
               existing_nullable=False)
    op.alter_column('api_tokens', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='활성화상태',
               existing_nullable=True)
    op.alter_column('api_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='생성일시',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('api_tokens', 'last_used_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='마지막사용일시',
               existing_nullable=True)
    op.alter_column('api_tokens', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='만료일시',
               existing_nullable=True)
    op.drop_table_comment(
        'api_tokens',
        existing_comment='API TOKEN',
        schema=None
    )
    op.alter_column('api_usage_logs', 'id',
               existing_type=sa.INTEGER(),
               comment='API사용로그일련번호',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('api_usage_logs', 'user_uuid',
               existing_type=sa.VARCHAR(length=36),
               comment='사용자고유식별자',
               existing_nullable=True)
    op.alter_column('api_usage_logs', 'api_key_hash',
               existing_type=sa.VARCHAR(length=64),
               comment='API키해시값',
               existing_nullable=True)
    op.alter_column('api_usage_logs', 'endpoint',
               existing_type=sa.VARCHAR(length=100),
               comment='API엔드포인트',
               existing_nullable=False)
    op.alter_column('api_usage_logs', 'method',
               existing_type=sa.VARCHAR(length=10),
               comment='HTTP메소드',
               existing_nullable=False)
    op.alter_column('api_usage_logs', 'status_code',
               existing_type=sa.INTEGER(),
               comment='HTTP상태코드',
               existing_nullable=False)
    op.alter_column('api_usage_logs', 'request_size',
               existing_type=sa.INTEGER(),
               comment='요청데이터크기',
               existing_nullable=True)
    op.alter_column('api_usage_logs', 'response_size',
               existing_type=sa.INTEGER(),
               comment='응답데이터크기',
               existing_nullable=True)
    op.alter_column('api_usage_logs', 'processing_time',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='처리시간',
               existing_nullable=True)
    op.alter_column('api_usage_logs', 'ip_address',
               existing_type=sa.VARCHAR(length=45),
               comment='클라이언트IP주소',
               existing_nullable=True)
    op.alter_column('api_usage_logs', 'user_agent',
               existing_type=sa.VARCHAR(length=500),
               comment='사용자에이전트',
               existing_nullable=True)
    op.alter_column('api_usage_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='생성일시',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('login_logs', 'id',
               existing_type=sa.INTEGER(),
               comment='로그인로그일련번호',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('login_logs', 'user_uuid',
               existing_type=sa.VARCHAR(length=36),
               comment='사용자고유식별자',
               existing_nullable=False)
    op.alter_column('login_logs', 'login_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='로그인시도시간',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('login_logs', 'ip_address',
               existing_type=sa.VARCHAR(length=45),
               comment='클라이언트IP주소',
               existing_nullable=True)
    op.alter_column('login_logs', 'user_agent',
               existing_type=sa.VARCHAR(length=500),
               comment='사용자에이전트',
               existing_nullable=True)
    op.alter_column('login_logs', 'success',
               existing_type=sa.BOOLEAN(),
               comment='로그인성공여부',
               existing_nullable=False)
    op.alter_column('login_logs', 'failure_reason',
               existing_type=sa.VARCHAR(length=255),
               comment='실패사유',
               existing_nullable=True)
    op.alter_column('login_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='생성일시',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('monthly_billings', 'id',
               existing_type=sa.INTEGER(),
               comment='월별빌링일련번호',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('monthly_billings', 'user_uuid',
               existing_type=sa.VARCHAR(length=36),
               comment='사용자고유식별자',
               existing_nullable=False)
    op.alter_column('monthly_billings', 'billing_year',
               existing_type=sa.INTEGER(),
               comment='청구연도',
               existing_nullable=False)
    op.alter_column('monthly_billings', 'billing_month',
               existing_type=sa.INTEGER(),
               comment='청구월',
               existing_nullable=False)
    op.alter_column('monthly_billings', 'plan_code',
               existing_type=sa.VARCHAR(length=50),
               comment='요금제코드',
               existing_nullable=False)
    op.alter_column('monthly_billings', 'total_minutes_used',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='총사용시간',
               existing_nullable=False)
    op.alter_column('monthly_billings', 'included_minutes',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='포함시간',
               existing_nullable=False)
    op.alter_column('monthly_billings', 'excess_minutes',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='초과사용시간',
               existing_nullable=False)
    op.alter_column('monthly_billings', 'total_requests',
               existing_type=sa.INTEGER(),
               comment='총요청건수',
               existing_nullable=False)
    op.alter_column('monthly_billings', 'base_subscription_fee',
               existing_type=sa.INTEGER(),
               comment='기본구독료',
               existing_nullable=False)
    op.alter_column('monthly_billings', 'per_minute_rate',
               existing_type=sa.INTEGER(),
               comment='분당기본요금',
               existing_nullable=True)
    op.alter_column('monthly_billings', 'excess_per_minute_rate',
               existing_type=sa.INTEGER(),
               comment='초과분당요금',
               existing_nullable=True)
    op.alter_column('monthly_billings', 'excess_usage_fee',
               existing_type=sa.INTEGER(),
               comment='초과사용료',
               existing_nullable=False)
    op.alter_column('monthly_billings', 'subtotal_amount',
               existing_type=sa.INTEGER(),
               comment='소계금액',
               existing_nullable=False)
    op.alter_column('monthly_billings', 'vat_amount',
               existing_type=sa.INTEGER(),
               comment='부가세',
               existing_nullable=False)
    op.alter_column('monthly_billings', 'total_billing_amount',
               existing_type=sa.INTEGER(),
               comment='총청구금액',
               existing_nullable=False)
    op.alter_column('monthly_billings', 'billing_status',
               existing_type=sa.VARCHAR(length=20),
               comment='청구상태',
               existing_nullable=False)
    op.alter_column('monthly_billings', 'payment_due_date',
               existing_type=sa.DATE(),
               comment='결제기한',
               existing_nullable=True)
    op.alter_column('monthly_billings', 'paid_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='결제완료시간',
               existing_nullable=True)
    op.alter_column('monthly_billings', 'billing_period_start',
               existing_type=sa.DATE(),
               comment='청구기간시작일',
               existing_nullable=False)
    op.alter_column('monthly_billings', 'billing_period_end',
               existing_type=sa.DATE(),
               comment='청구기간종료일',
               existing_nullable=False)
    op.alter_column('monthly_billings', 'generated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='청구서생성시간',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('monthly_billings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='생성일시',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('monthly_billings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='수정일시',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('overage_payments', 'id',
               existing_type=sa.INTEGER(),
               comment='초과결제일련번호',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('overage_payments', 'payment_id',
               existing_type=sa.VARCHAR(length=50),
               comment='결제식별자',
               existing_nullable=False)
    op.alter_column('overage_payments', 'plan_code',
               existing_type=sa.VARCHAR(length=50),
               comment='요금제코드',
               existing_nullable=False)
    op.alter_column('overage_payments', 'unit_price',
               existing_type=sa.INTEGER(),
               comment='기본단가',
               existing_nullable=False)
    op.alter_column('overage_payments', 'overage_unit_price',
               existing_type=sa.INTEGER(),
               comment='초과단가',
               existing_nullable=False)
    op.alter_column('overage_payments', 'overage_tokens',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='초과토큰시간',
               existing_nullable=False)
    op.alter_column('overage_payments', 'amount',
               existing_type=sa.INTEGER(),
               comment='총초과사용료',
               existing_nullable=False)
    op.alter_column('overage_payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='생성일시',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('overage_payments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='수정일시',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('payments', 'payment_id',
               existing_type=sa.VARCHAR(length=50),
               comment='결재번호',
               existing_nullable=False)
    op.alter_column('payments', 'user_uuid',
               existing_type=sa.VARCHAR(length=36),
               comment='사용자고유식별자',
               existing_nullable=False)
    op.alter_column('payments', 'plan_code',
               existing_type=sa.VARCHAR(length=50),
               comment='요금제코드',
               existing_nullable=False)
    op.alter_column('payments', 'supply_amount',
               existing_type=sa.INTEGER(),
               comment='공급가액',
               existing_nullable=False)
    op.alter_column('payments', 'vat_amount',
               existing_type=sa.INTEGER(),
               comment='부가세',
               existing_nullable=False)
    op.alter_column('payments', 'total_amount',
               existing_type=sa.INTEGER(),
               comment='합계금액',
               existing_nullable=False)
    op.alter_column('payments', 'payment_status',
               existing_type=sa.VARCHAR(length=20),
               comment='결재상태',
               existing_nullable=False)
    op.alter_column('payments', 'payment_method',
               existing_type=sa.VARCHAR(length=50),
               comment='결재수단',
               existing_nullable=True)
    op.alter_column('payments', 'payment_type',
               existing_type=sa.VARCHAR(length=50),
               comment='결재구분',
               existing_nullable=False)
    op.alter_column('payments', 'external_payment_id',
               existing_type=sa.VARCHAR(length=100),
               comment='외부결재시스템ID',
               existing_nullable=True)
    op.alter_column('payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='생성일시',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('payments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='수정일시',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('payments', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='완료일시',
               existing_nullable=True)
    op.alter_column('service_tokens', 'id',
               existing_type=sa.INTEGER(),
               comment='서비스토큰일련번호',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('service_tokens', 'user_uuid',
               existing_type=sa.VARCHAR(length=36),
               comment='사용자고유식별자',
               existing_nullable=False)
    op.alter_column('service_tokens', 'token_id',
               existing_type=sa.VARCHAR(length=100),
               comment='토큰식별자',
               existing_nullable=False)
    op.alter_column('service_tokens', 'quota_tokens',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='구독할당토큰',
               existing_nullable=False)
    op.alter_column('service_tokens', 'used_tokens',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='누적사용토큰',
               existing_nullable=False)
    op.alter_column('service_tokens', 'token_expiry_date',
               existing_type=sa.DATE(),
               comment='토큰종료일자',
               existing_nullable=False)
    op.alter_column('service_tokens', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='상태',
               existing_nullable=False)
    op.alter_column('service_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='생성일시',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('service_tokens', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='수정일시',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('subscription_payments', 'id',
               existing_type=sa.INTEGER(),
               comment='구독결제일련번호',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('subscription_payments', 'payment_id',
               existing_type=sa.VARCHAR(length=50),
               comment='결제식별자',
               existing_nullable=False)
    op.alter_column('subscription_payments', 'plan_code',
               existing_type=sa.VARCHAR(length=50),
               comment='요금제코드',
               existing_nullable=False)
    op.alter_column('subscription_payments', 'unit_price',
               existing_type=sa.INTEGER(),
               comment='단가',
               existing_nullable=False)
    op.alter_column('subscription_payments', 'quantity',
               existing_type=sa.INTEGER(),
               comment='인원수',
               existing_nullable=False)
    op.alter_column('subscription_payments', 'amount',
               existing_type=sa.INTEGER(),
               comment='금액',
               existing_nullable=False)
    op.alter_column('subscription_payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='생성일시',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('subscription_payments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='수정일시',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('subscription_plans', 'id',
               existing_type=sa.INTEGER(),
               comment='구독요금일련번호',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('subscription_plans', 'plan_code',
               existing_type=sa.VARCHAR(length=50),
               comment='요금제코드',
               existing_nullable=False)
    op.alter_column('subscription_plans', 'plan_description',
               existing_type=sa.VARCHAR(length=500),
               comment='요금제설명',
               existing_nullable=False)
    op.alter_column('subscription_plans', 'monthly_price',
               existing_type=sa.INTEGER(),
               comment='월구독금액',
               existing_nullable=False)
    op.alter_column('subscription_plans', 'monthly_service_tokens',
               existing_type=sa.INTEGER(),
               comment='월제공서비스토큰수',
               existing_nullable=False)
    op.alter_column('subscription_plans', 'per_minute_rate',
               existing_type=sa.INTEGER(),
               comment='분당요금',
               existing_nullable=True)
    op.alter_column('subscription_plans', 'overage_per_minute_rate',
               existing_type=sa.INTEGER(),
               comment='초과분당요금',
               existing_nullable=True)
    op.alter_column('subscription_plans', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='활성화상태',
               existing_nullable=True)
    op.alter_column('subscription_plans', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='생성일시',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('subscription_plans', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='수정일시',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('token_payments', 'id',
               existing_type=sa.INTEGER(),
               comment='토큰결제일련번호',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('token_payments', 'payment_id',
               existing_type=sa.VARCHAR(length=50),
               comment='결제식별자',
               existing_nullable=False)
    op.alter_column('token_payments', 'token_quantity',
               existing_type=sa.INTEGER(),
               comment='토큰수량',
               existing_nullable=False)
    op.alter_column('token_payments', 'token_unit_price',
               existing_type=sa.INTEGER(),
               comment='토큰단가',
               existing_nullable=False)
    op.alter_column('token_payments', 'amount',
               existing_type=sa.INTEGER(),
               comment='총금액',
               existing_nullable=False)
    op.alter_column('token_payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='생성일시',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('token_payments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='수정일시',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('token_usage_history', 'id',
               existing_type=sa.INTEGER(),
               comment='토큰사용내역일련번호',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('token_usage_history', 'token_id',
               existing_type=sa.VARCHAR(length=100),
               comment='토큰식별자',
               existing_nullable=False)
    op.alter_column('token_usage_history', 'used_tokens',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='사용토큰수량',
               existing_nullable=False)
    op.alter_column('token_usage_history', 'request_id',
               existing_type=sa.VARCHAR(length=100),
               comment='요청고유식별자',
               existing_nullable=False)
    op.alter_column('token_usage_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='생성일시',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('transcription_requests', 'request_id',
               existing_type=sa.VARCHAR(length=50),
               comment='요청식별자',
               existing_nullable=False)
    op.alter_column('transcription_requests', 'user_uuid',
               existing_type=sa.VARCHAR(length=36),
               comment='사용자고유식별자',
               existing_nullable=True)
    op.alter_column('transcription_requests', 'filename',
               existing_type=sa.VARCHAR(length=255),
               comment='파일명',
               existing_nullable=False)
    op.alter_column('transcription_requests', 'file_size',
               existing_type=sa.INTEGER(),
               comment='파일크기',
               existing_nullable=False)
    op.alter_column('transcription_requests', 'file_extension',
               existing_type=sa.VARCHAR(length=10),
               comment='파일확장자',
               existing_nullable=False)
    op.alter_column('transcription_requests', 'duration',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='재생시간',
               existing_nullable=True)
    op.alter_column('transcription_requests', 'service_provider',
               existing_type=sa.VARCHAR(length=50),
               comment='서비스제공업체',
               existing_nullable=True)
    op.alter_column('transcription_requests', 'client_ip',
               existing_type=sa.VARCHAR(length=50),
               comment='클라이언트IP주소',
               existing_nullable=True)
    op.alter_column('transcription_requests', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment='처리상태',
               existing_nullable=False)
    op.alter_column('transcription_requests', 'response_rid',
               existing_type=sa.VARCHAR(length=100),
               comment='응답식별자',
               existing_nullable=True)
    op.alter_column('transcription_requests', 'processing_time',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='처리시간',
               existing_nullable=True)
    op.alter_column('transcription_requests', 'error_message',
               existing_type=sa.TEXT(),
               comment='오류메시지',
               existing_nullable=True)
    op.alter_column('transcription_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='생성일시',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('transcription_requests', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='완료일시',
               existing_nullable=True)
    op.alter_column('transcription_responses', 'id',
               existing_type=sa.INTEGER(),
               comment='응답일련번호',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('transcription_responses', 'request_id',
               existing_type=sa.VARCHAR(length=50),
               comment='요청식별자',
               existing_nullable=False)
    op.alter_column('transcription_responses', 'service_provider',
               existing_type=sa.VARCHAR(length=50),
               comment='서비스제공업체',
               existing_nullable=True)
    op.alter_column('transcription_responses', 'transcribed_text',
               existing_type=sa.TEXT(),
               comment='변환텍스트',
               existing_nullable=True)
    op.alter_column('transcription_responses', 'summary_text',
               existing_type=sa.TEXT(),
               comment='요약텍스트',
               existing_nullable=True)
    op.alter_column('transcription_responses', 'confidence_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='신뢰도점수',
               existing_nullable=True)
    op.alter_column('transcription_responses', 'language_detected',
               existing_type=sa.VARCHAR(length=10),
               comment='감지언어',
               existing_nullable=True)
    op.alter_column('transcription_responses', 'duration',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='오디오길이',
               existing_nullable=True)
    op.alter_column('transcription_responses', 'audio_duration_minutes',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='음성길이분',
               existing_nullable=True)
    op.alter_column('transcription_responses', 'word_count',
               existing_type=sa.INTEGER(),
               comment='단어수',
               existing_nullable=True)
    op.alter_column('transcription_responses', 'tokens_used',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='사용토큰수',
               existing_nullable=True)
    op.alter_column('transcription_responses', 'response_data',
               existing_type=sa.TEXT(),
               comment='원본응답데이터',
               existing_nullable=True)
    op.alter_column('transcription_responses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='생성일시',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               comment='사용자일련번호',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('users_id_seq'::regclass)"))
    op.alter_column('users', 'user_id',
               existing_type=sa.VARCHAR(length=100),
               comment='사용자아이디',
               existing_nullable=False)
    op.alter_column('users', 'user_uuid',
               existing_type=sa.VARCHAR(length=36),
               comment='사용자고유식별자',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='이메일주소',
               existing_nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='사용자명',
               existing_nullable=False)
    op.alter_column('users', 'user_type',
               existing_type=sa.VARCHAR(length=20),
               comment='사용자유형',
               existing_nullable=False)
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               comment='전화번호',
               existing_nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment='비밀번호해시',
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='활성화상태',
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='생성일시',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='수정일시',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='수정일시',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='생성일시',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='활성화상태',
               existing_nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='비밀번호해시',
               existing_nullable=False)
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='전화번호',
               existing_nullable=True)
    op.alter_column('users', 'user_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='사용자유형',
               existing_nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='사용자명',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='이메일주소',
               existing_nullable=False)
    op.alter_column('users', 'user_uuid',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='사용자고유식별자',
               existing_nullable=False)
    op.alter_column('users', 'user_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='사용자아이디',
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='사용자일련번호',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('users_id_seq'::regclass)"))
    op.alter_column('transcription_responses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='생성일시',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('transcription_responses', 'response_data',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='원본응답데이터',
               existing_nullable=True)
    op.alter_column('transcription_responses', 'tokens_used',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='사용토큰수',
               existing_nullable=True)
    op.alter_column('transcription_responses', 'word_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='단어수',
               existing_nullable=True)
    op.alter_column('transcription_responses', 'audio_duration_minutes',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='음성길이분',
               existing_nullable=True)
    op.alter_column('transcription_responses', 'duration',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='오디오길이',
               existing_nullable=True)
    op.alter_column('transcription_responses', 'language_detected',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='감지언어',
               existing_nullable=True)
    op.alter_column('transcription_responses', 'confidence_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='신뢰도점수',
               existing_nullable=True)
    op.alter_column('transcription_responses', 'summary_text',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='요약텍스트',
               existing_nullable=True)
    op.alter_column('transcription_responses', 'transcribed_text',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='변환텍스트',
               existing_nullable=True)
    op.alter_column('transcription_responses', 'service_provider',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='서비스제공업체',
               existing_nullable=True)
    op.alter_column('transcription_responses', 'request_id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='요청식별자',
               existing_nullable=False)
    op.alter_column('transcription_responses', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='응답일련번호',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('transcription_requests', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='완료일시',
               existing_nullable=True)
    op.alter_column('transcription_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='생성일시',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('transcription_requests', 'error_message',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='오류메시지',
               existing_nullable=True)
    op.alter_column('transcription_requests', 'processing_time',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='처리시간',
               existing_nullable=True)
    op.alter_column('transcription_requests', 'response_rid',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='응답식별자',
               existing_nullable=True)
    op.alter_column('transcription_requests', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='처리상태',
               existing_nullable=False)
    op.alter_column('transcription_requests', 'client_ip',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='클라이언트IP주소',
               existing_nullable=True)
    op.alter_column('transcription_requests', 'service_provider',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='서비스제공업체',
               existing_nullable=True)
    op.alter_column('transcription_requests', 'duration',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='재생시간',
               existing_nullable=True)
    op.alter_column('transcription_requests', 'file_extension',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='파일확장자',
               existing_nullable=False)
    op.alter_column('transcription_requests', 'file_size',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='파일크기',
               existing_nullable=False)
    op.alter_column('transcription_requests', 'filename',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='파일명',
               existing_nullable=False)
    op.alter_column('transcription_requests', 'user_uuid',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='사용자고유식별자',
               existing_nullable=True)
    op.alter_column('transcription_requests', 'request_id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='요청식별자',
               existing_nullable=False)
    op.alter_column('token_usage_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='생성일시',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('token_usage_history', 'request_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='요청고유식별자',
               existing_nullable=False)
    op.alter_column('token_usage_history', 'used_tokens',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='사용토큰수량',
               existing_nullable=False)
    op.alter_column('token_usage_history', 'token_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='토큰식별자',
               existing_nullable=False)
    op.alter_column('token_usage_history', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='토큰사용내역일련번호',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('token_payments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='수정일시',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('token_payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='생성일시',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('token_payments', 'amount',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='총금액',
               existing_nullable=False)
    op.alter_column('token_payments', 'token_unit_price',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='토큰단가',
               existing_nullable=False)
    op.alter_column('token_payments', 'token_quantity',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='토큰수량',
               existing_nullable=False)
    op.alter_column('token_payments', 'payment_id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='결제식별자',
               existing_nullable=False)
    op.alter_column('token_payments', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='토큰결제일련번호',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('subscription_plans', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='수정일시',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('subscription_plans', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='생성일시',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('subscription_plans', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='활성화상태',
               existing_nullable=True)
    op.alter_column('subscription_plans', 'overage_per_minute_rate',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='초과분당요금',
               existing_nullable=True)
    op.alter_column('subscription_plans', 'per_minute_rate',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='분당요금',
               existing_nullable=True)
    op.alter_column('subscription_plans', 'monthly_service_tokens',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='월제공서비스토큰수',
               existing_nullable=False)
    op.alter_column('subscription_plans', 'monthly_price',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='월구독금액',
               existing_nullable=False)
    op.alter_column('subscription_plans', 'plan_description',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='요금제설명',
               existing_nullable=False)
    op.alter_column('subscription_plans', 'plan_code',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='요금제코드',
               existing_nullable=False)
    op.alter_column('subscription_plans', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='구독요금일련번호',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('subscription_payments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='수정일시',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('subscription_payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='생성일시',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('subscription_payments', 'amount',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='금액',
               existing_nullable=False)
    op.alter_column('subscription_payments', 'quantity',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='인원수',
               existing_nullable=False)
    op.alter_column('subscription_payments', 'unit_price',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='단가',
               existing_nullable=False)
    op.alter_column('subscription_payments', 'plan_code',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='요금제코드',
               existing_nullable=False)
    op.alter_column('subscription_payments', 'payment_id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='결제식별자',
               existing_nullable=False)
    op.alter_column('subscription_payments', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='구독결제일련번호',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('service_tokens', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='수정일시',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('service_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='생성일시',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('service_tokens', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='상태',
               existing_nullable=False)
    op.alter_column('service_tokens', 'token_expiry_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='토큰종료일자',
               existing_nullable=False)
    op.alter_column('service_tokens', 'used_tokens',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='누적사용토큰',
               existing_nullable=False)
    op.alter_column('service_tokens', 'quota_tokens',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='구독할당토큰',
               existing_nullable=False)
    op.alter_column('service_tokens', 'token_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='토큰식별자',
               existing_nullable=False)
    op.alter_column('service_tokens', 'user_uuid',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='사용자고유식별자',
               existing_nullable=False)
    op.alter_column('service_tokens', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='서비스토큰일련번호',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('payments', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='완료일시',
               existing_nullable=True)
    op.alter_column('payments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='수정일시',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='생성일시',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('payments', 'external_payment_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='외부결재시스템ID',
               existing_nullable=True)
    op.alter_column('payments', 'payment_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='결재구분',
               existing_nullable=False)
    op.alter_column('payments', 'payment_method',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='결재수단',
               existing_nullable=True)
    op.alter_column('payments', 'payment_status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='결재상태',
               existing_nullable=False)
    op.alter_column('payments', 'total_amount',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='합계금액',
               existing_nullable=False)
    op.alter_column('payments', 'vat_amount',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='부가세',
               existing_nullable=False)
    op.alter_column('payments', 'supply_amount',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='공급가액',
               existing_nullable=False)
    op.alter_column('payments', 'plan_code',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='요금제코드',
               existing_nullable=False)
    op.alter_column('payments', 'user_uuid',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='사용자고유식별자',
               existing_nullable=False)
    op.alter_column('payments', 'payment_id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='결재번호',
               existing_nullable=False)
    op.alter_column('overage_payments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='수정일시',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('overage_payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='생성일시',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('overage_payments', 'amount',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='총초과사용료',
               existing_nullable=False)
    op.alter_column('overage_payments', 'overage_tokens',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='초과토큰시간',
               existing_nullable=False)
    op.alter_column('overage_payments', 'overage_unit_price',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='초과단가',
               existing_nullable=False)
    op.alter_column('overage_payments', 'unit_price',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='기본단가',
               existing_nullable=False)
    op.alter_column('overage_payments', 'plan_code',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='요금제코드',
               existing_nullable=False)
    op.alter_column('overage_payments', 'payment_id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='결제식별자',
               existing_nullable=False)
    op.alter_column('overage_payments', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='초과결제일련번호',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('monthly_billings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='수정일시',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('monthly_billings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='생성일시',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('monthly_billings', 'generated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='청구서생성시간',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('monthly_billings', 'billing_period_end',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='청구기간종료일',
               existing_nullable=False)
    op.alter_column('monthly_billings', 'billing_period_start',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='청구기간시작일',
               existing_nullable=False)
    op.alter_column('monthly_billings', 'paid_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='결제완료시간',
               existing_nullable=True)
    op.alter_column('monthly_billings', 'payment_due_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='결제기한',
               existing_nullable=True)
    op.alter_column('monthly_billings', 'billing_status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='청구상태',
               existing_nullable=False)
    op.alter_column('monthly_billings', 'total_billing_amount',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='총청구금액',
               existing_nullable=False)
    op.alter_column('monthly_billings', 'vat_amount',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='부가세',
               existing_nullable=False)
    op.alter_column('monthly_billings', 'subtotal_amount',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='소계금액',
               existing_nullable=False)
    op.alter_column('monthly_billings', 'excess_usage_fee',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='초과사용료',
               existing_nullable=False)
    op.alter_column('monthly_billings', 'excess_per_minute_rate',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='초과분당요금',
               existing_nullable=True)
    op.alter_column('monthly_billings', 'per_minute_rate',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='분당기본요금',
               existing_nullable=True)
    op.alter_column('monthly_billings', 'base_subscription_fee',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='기본구독료',
               existing_nullable=False)
    op.alter_column('monthly_billings', 'total_requests',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='총요청건수',
               existing_nullable=False)
    op.alter_column('monthly_billings', 'excess_minutes',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='초과사용시간',
               existing_nullable=False)
    op.alter_column('monthly_billings', 'included_minutes',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='포함시간',
               existing_nullable=False)
    op.alter_column('monthly_billings', 'total_minutes_used',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='총사용시간',
               existing_nullable=False)
    op.alter_column('monthly_billings', 'plan_code',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='요금제코드',
               existing_nullable=False)
    op.alter_column('monthly_billings', 'billing_month',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='청구월',
               existing_nullable=False)
    op.alter_column('monthly_billings', 'billing_year',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='청구연도',
               existing_nullable=False)
    op.alter_column('monthly_billings', 'user_uuid',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='사용자고유식별자',
               existing_nullable=False)
    op.alter_column('monthly_billings', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='월별빌링일련번호',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('login_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='생성일시',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('login_logs', 'failure_reason',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='실패사유',
               existing_nullable=True)
    op.alter_column('login_logs', 'success',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='로그인성공여부',
               existing_nullable=False)
    op.alter_column('login_logs', 'user_agent',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='사용자에이전트',
               existing_nullable=True)
    op.alter_column('login_logs', 'ip_address',
               existing_type=sa.VARCHAR(length=45),
               comment=None,
               existing_comment='클라이언트IP주소',
               existing_nullable=True)
    op.alter_column('login_logs', 'login_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='로그인시도시간',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('login_logs', 'user_uuid',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='사용자고유식별자',
               existing_nullable=False)
    op.alter_column('login_logs', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='로그인로그일련번호',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('api_usage_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='생성일시',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('api_usage_logs', 'user_agent',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='사용자에이전트',
               existing_nullable=True)
    op.alter_column('api_usage_logs', 'ip_address',
               existing_type=sa.VARCHAR(length=45),
               comment=None,
               existing_comment='클라이언트IP주소',
               existing_nullable=True)
    op.alter_column('api_usage_logs', 'processing_time',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='처리시간',
               existing_nullable=True)
    op.alter_column('api_usage_logs', 'response_size',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='응답데이터크기',
               existing_nullable=True)
    op.alter_column('api_usage_logs', 'request_size',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='요청데이터크기',
               existing_nullable=True)
    op.alter_column('api_usage_logs', 'status_code',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='HTTP상태코드',
               existing_nullable=False)
    op.alter_column('api_usage_logs', 'method',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='HTTP메소드',
               existing_nullable=False)
    op.alter_column('api_usage_logs', 'endpoint',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='API엔드포인트',
               existing_nullable=False)
    op.alter_column('api_usage_logs', 'api_key_hash',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='API키해시값',
               existing_nullable=True)
    op.alter_column('api_usage_logs', 'user_uuid',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='사용자고유식별자',
               existing_nullable=True)
    op.alter_column('api_usage_logs', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='API사용로그일련번호',
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'api_tokens',
        'API TOKEN',
        existing_comment=None,
        schema=None
    )
    op.alter_column('api_tokens', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='만료일시',
               existing_nullable=True)
    op.alter_column('api_tokens', 'last_used_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='마지막사용일시',
               existing_nullable=True)
    op.alter_column('api_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='생성일시',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('api_tokens', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='활성화상태',
               existing_nullable=True)
    op.alter_column('api_tokens', 'api_key',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='API키',
               existing_nullable=False)
    op.alter_column('api_tokens', 'token_key',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='토큰키해시값',
               existing_nullable=False)
    op.alter_column('api_tokens', 'token_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='토큰명',
               existing_nullable=True)
    op.alter_column('api_tokens', 'token_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='토큰식별자',
               existing_nullable=False)
    op.alter_column('api_tokens', 'user_uuid',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='사용자고유식별자',
               existing_nullable=False)
    op.alter_column('api_tokens', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='API토큰일련번호',
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
