"""Update service_tokens status constraint

Revision ID: 5cb265589888
Revises: 78f7cdf2dfc7
Create Date: 2025-08-22 14:46:07.948020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cb265589888'
down_revision: Union[str, None] = '78f7cdf2dfc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'api_tokens',
        '사용자별 API 인증 토큰을 관리하는 테이블',
        existing_comment=None,
        schema=None
    )
    op.drop_index('ix_subscription_plans_plan_code', table_name='subscription_plans')
    op.create_index(op.f('ix_subscription_plans_plan_code'), 'subscription_plans', ['plan_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscription_plans_plan_code'), table_name='subscription_plans')
    op.create_index('ix_subscription_plans_plan_code', 'subscription_plans', ['plan_code'], unique=True)
    op.drop_table_comment(
        'api_tokens',
        existing_comment='사용자별 API 인증 토큰을 관리하는 테이블',
        schema=None
    )
    # ### end Alembic commands ###
