"""Add description column to api_tokens table

Revision ID: c28b8b26b286
Revises: 57079e0a7c7f
Create Date: 2025-09-25 09:26:57.340895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c28b8b26b286'
down_revision: Union[str, None] = '57079e0a7c7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_tokens', sa.Column('description', sa.String(length=4000), nullable=True, comment='상세정보'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_tokens', 'description')
    # ### end Alembic commands ###
